package model;
// Generated 11/02/2016 16:06:43 by Hibernate Tools 4.3.1



/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private int idade;
     private String sexo;

    public Pessoa() {
    }

    public Pessoa(String nome, int idade, String sexo) {
       this.nome = nome;
       this.idade = idade;
       this.sexo = sexo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


